base_url = "https://selectiveduplicate.github.io/blog"
title = "Sakib's blog"
description = "A digital diary of programming, literature, films, and whatever else."
author = "Abu Sakib"
theme = "terminus"

compile_sass = true
generate_feeds = true
build_search_index = true

[markdown]
render_emoji = true
bottom_footnotes = true
lazy_async_image = true
github_alerts = true

[markdown.highlighting]
style = "inline"
extra_themes = ["syntaxes/monokai-classic.json"]
theme = "monokai-classic"

[extra]
layout = "center"
show_default_author = true
copy_button = true
favicon_emoji = "✍️"
feed_icon = true
copyright = "© $YEAR $AUTHOR :: Powered by [Zola](https://www.getzola.org) :: Theme by [ebkalderon](https://eyalkalderon.com)"

main_menu = [
    { name = "about", url = "about", trailing_slash = true },
    { name = "github", url = "https://github.com/selectiveduplicate", new_tab = true },
    { name = "twitter", url = "https://twitter.com/Slctvdplcate", new_tab = true },
]

socials = [
    { name = "github", url = "https://github.com/selectiveduplicate" },
    { name = "linkedin", url = "https://www.linkedin.com/in/selectiveduplicate/" },
]

[extra.content_security_policy]
enable = true
allowed_domains = []

[extra.responsive_images]
widths = [640, 784, 1280, 1920, 2560]
fallback_width = 1280
